server:
  port: 5000
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:weather_db
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

weather:
  forecast:
    url: http://apiadvisor.climatempo.com.br/api/v1/forecast/locale/
    token: b22460a8b91ac5f1d48f5b7029891b53